### ISSUE TITLE
JSON format

### ISSUE THREAD

**Issue by elexpander** [lochiiconnectivity/pyOffice365#2]
I assume the output of these functions is in JSON format but I couldn't parse it.

From http://www.json.org/:
> A value can be a string in double quotes, or a number, or true or false or null, or an object or an array. 

All strings are between single quotes, true and false are in Capital, None should be replaced with null.

**Comment by lochiiconnectivity** [comment]
do you have an example method which returns such a response? and can you provide an anonymised copy of such a response ?

**Comment by lochiiconnectivity** [comment]
i think there is some ambiguity in the documentation , these calls actually return an object (which is just a fancy nested dictionary) and the examples are in JSON just to standardise them for use by the test suite outside the library , if you check type(o.get_tenant()) you should see this. Apologies , I will clarify the documentation.

**Comment by lochiiconnectivity** [comment]
Closing this issue
